/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Calculadora_IMC.imc.view;

/**
 *
 * @author Santiago González
 */
public class CalculadoraView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraView.class.getName());

    /**
     * Creates new form IMCView
     */
    public CalculadoraView() {
        initComponents();
        
        // Icono fuerza
        javax.swing.ImageIcon iconoOriginalMusculo = (javax.swing.ImageIcon) lblIconoMusculo.getIcon();
        if (iconoOriginalMusculo != null) {
            // Escalar la imagen del icono de fuerza para que se ajuste al tamaño del JLabel
            java.awt.Image imagenEscalada = iconoOriginalMusculo.getImage().getScaledInstance(
                lblIconoMusculo.getWidth(), 
                lblIconoMusculo.getHeight(), 
                java.awt.Image.SCALE_SMOOTH
            );

            lblIconoMusculo.setIcon(new javax.swing.ImageIcon(imagenEscalada)); // Establecer el icono escalado en el JLabel
        }
        
        // Icono grasa-corporal
        javax.swing.ImageIcon iconoOriginalGrasa = (javax.swing.ImageIcon) lblIconoGrasaCorporal.getIcon();
        if (iconoOriginalGrasa != null) {
            // Escalar la imagen del icono de grasa-corporal para que se ajuste al tamaño del JLabel
            java.awt.Image imagenEscalada = iconoOriginalGrasa.getImage().getScaledInstance(
                lblIconoGrasaCorporal.getWidth(), 
                lblIconoGrasaCorporal.getHeight(), 
                java.awt.Image.SCALE_SMOOTH
            );

            lblIconoGrasaCorporal.setIcon(new javax.swing.ImageIcon(imagenEscalada)); // Establecer el icono escalado en el JLabel
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlPeso = new javax.swing.JPanel();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        pnlAltura = new javax.swing.JPanel();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblClasificacion = new javax.swing.JLabel();
        lblIconoMusculo = new javax.swing.JLabel();
        lblIconoGrasaCorporal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CALCULADORA DE IMC");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(40, 20, 410, 48);

        lblPeso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPeso.setText("Peso (kg):");

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlPesoLayout = new javax.swing.GroupLayout(pnlPeso);
        pnlPeso.setLayout(pnlPesoLayout);
        pnlPesoLayout.setHorizontalGroup(
            pnlPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPeso)
                .addGap(18, 18, 18)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlPesoLayout.setVerticalGroup(
            pnlPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso)
                    .addComponent(lblPeso))
                .addContainerGap())
        );

        getContentPane().add(pnlPeso);
        pnlPeso.setBounds(120, 100, 253, 45);

        lblAltura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAltura.setText("Altura (m):");

        txtAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlAlturaLayout = new javax.swing.GroupLayout(pnlAltura);
        pnlAltura.setLayout(pnlAlturaLayout);
        pnlAlturaLayout.setHorizontalGroup(
            pnlAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAlturaLayout.setVerticalGroup(
            pnlAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura))
                .addContainerGap())
        );

        getContentPane().add(pnlAltura);
        pnlAltura.setBounds(120, 160, 242, 43);

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(174, 225, 150, 43);

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblResultado);
        lblResultado.setBounds(130, 280, 230, 31);

        lblClasificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClasificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblClasificacion);
        lblClasificacion.setBounds(130, 320, 230, 30);

        lblIconoMusculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIconoMusculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Calculadora_IMC/imc/view/img/fuerza.png"))); // NOI18N
        getContentPane().add(lblIconoMusculo);
        lblIconoMusculo.setBounds(400, 260, 80, 80);

        lblIconoGrasaCorporal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIconoGrasaCorporal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Calculadora_IMC/imc/view/img/grasa-corporal.png"))); // NOI18N
        getContentPane().add(lblIconoGrasaCorporal);
        lblIconoGrasaCorporal.setBounds(-10, 260, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblAltura;
    public javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblIconoGrasaCorporal;
    private javax.swing.JLabel lblIconoMusculo;
    private javax.swing.JLabel lblPeso;
    public javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAltura;
    private javax.swing.JPanel pnlPeso;
    public javax.swing.JTextField txtAltura;
    public javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
